substitutions:
  name: boneio-8-s-01
  friendly_name: 'BoneIO ESP 8x10A Switches'
  serial_prefix: 'espm' #Don't change it.

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: true
  project:
    name: boneio.8_10-switches
    version: '0.1'

esp32:
  board: esp32dev

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-8x10A_v0_1.yaml@latest
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.4.0
    files:
      [
        'devices/buzzer.yaml',
        'devices/serial_no.yaml',
        'devices/dimmer_i2c.yaml',
        'devices_v0_7-v0_9/lm75b.yaml',
      ]

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome

web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time

mcp23017:
  - id: 'mcp1'
    address: 0x20

# Individual outputs
switch:
  - platform: gpio
    name: 'OUT 1'
    id: out_01
    pin:
      mcp23xxx: mcp1
      number: 8
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: 'OUT 2'
    id: out_02
    pin:
      mcp23xxx: mcp1
      number: 9
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: 'OUT 3'
    id: out_03
    pin:
      mcp23xxx: mcp1
      number: 10
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: 'OUT 4'
    id: out_04
    pin:
      mcp23xxx: mcp1
      number: 11
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: 'OUT 5'
    id: out_05
    pin:
      mcp23xxx: mcp1
      number: 12
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: 'OUT 6'
    id: out_06
    pin:
      mcp23xxx: mcp1
      number: 13
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: 'OUT 7'
    id: out_07
    pin:
      mcp23xxx: mcp1
      number: 14
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: 'OUT 8'
    id: out_08
    pin:
      mcp23xxx: mcp1
      number: 15
      mode:
        output: true
      inverted: false

binary_sensor:
  - platform: gpio
    name: 'IN 01'
    id: in_01
    pin:
      mcp23xxx: mcp1
      number: 0
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: 'IN 02'
    id: in_02
    pin:
      mcp23xxx: mcp1
      number: 1
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: 'IN 03'
    id: in_03
    pin:
      mcp23xxx: mcp1
      number: 2
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: 'IN 04'
    id: in_04
    pin:
      mcp23xxx: mcp1
      number: 3
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: 'IN 05'
    id: in_05
    pin:
      mcp23xxx: mcp1
      number: 4
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: 'IN 06'
    id: in_06
    pin:
      mcp23xxx: mcp1
      number: 5
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: 'IN 07'
    id: in_07
    pin:
      mcp23xxx: mcp1
      number: 6
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: 'IN 08'
    id: in_08
    pin:
      mcp23xxx: mcp1
      number: 7
      mode:
        input: true
      inverted: false
