substitutions:
  name: boneio-dr-rgbw-03
  friendly_name: 'BoneIO Dimmer LED'
  serial_prefix: 'dim' #Don't change it.

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: true
  project:
    name: boneio.dimmer-led
    version: '0.3'

esp32:
  board: esp32dev
  framework:                                                                            
    type: esp-idf

external_components:
  - source: github://boneIO-eu/esphome-LM75@main #Original source and thank you note for BTomala https://github.com/boneIO-eu/esphome-lm75
    components: [lm75]

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files:
      [
        'devices/serial_no.yaml',
        'devices/dimmer_i2c.yaml',
        'devices/dimmer_ina219.yaml',
        'boards/dimmer_output.yaml',
      ]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-dimmer_2rgbw-v0_3.yaml@latest
  import_full_config: true

pcf8574:
  - id: 'pcf_inputs'
    address: 0x38

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true

text_sensor:
  - platform: version
    name: 'boneio-dimmer- Version'
    icon: mdi:cube-outline
    entity_category: diagnostic
  - platform: ethernet_info
    ip_address:
      entity_category: diagnostic
      name: boneio-dimmer IP
  - platform: template
    name: 'Hostname'
    id: hostname
    entity_category: diagnostic
    lambda: |-
      return id(eth).get_use_address();
    update_interval: 5min

binary_sensor:
  - platform: gpio
    name: 'IN_01'
    pin:
      pcf8574: pcf_inputs
      number: 1
      mode:
        input: true
      inverted: true
    on_multi_click:
      - timing: # double click
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: rgbw_l
          - logger.log: 'Double Click'
      - timing: # single click
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - light.toggle: rgbw_l
          - logger.log: 'Single Click'
      - timing: # long click
          - ON for at least 1.4s
        then:
          - light.toggle: rgbw_r
          - logger.log: 'Long Click'
  - platform: gpio
    name: 'IN_02'
    pin:
      pcf8574: pcf_inputs
      number: 2
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: 'IN_03'
    pin:
      pcf8574: pcf_inputs
      number: 3
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: 'IN_04'
    pin:
      pcf8574: pcf_inputs
      number: 4
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: 'IN_05'
    pin:
      number: 36
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: 'IN_06'
    pin:
      number: 39
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: 'IN_07'
    pin:
      number: 34
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: 'IN_08'
    pin:
      number: 35
      mode:
        input: true
      inverted: true

light:
  - platform: rgbw
    id: rgbw_l
    name: 'RGBW L'
    red: chl01
    green: chl02
    blue: chl03
    white: chl04
    default_transition_length: 2s
    gamma_correct: 0
  - platform: rgbw
    id: rgbw_r
    name: 'RGBW R'
    red: chr01
    green: chr02
    blue: chr03
    white: chr04
    default_transition_length: 2s
    gamma_correct: 0

sensor:
  - platform: lm75
    id: boneIO_temp
    name: 'Temperature'
    update_interval: 30s
    entity_category: diagnostic
    on_value_range:
      - above: 70.0
        then:
          - switch.turn_on: buzzer
      - below: 70.0
        then:
          - switch.turn_off: buzzer

switch:
  - platform: gpio
    id: buzzer
    name: 'Buzzer'
    pin:
      pcf8574: pcf_inputs
      number: 0
      mode:
        output: true
      inverted: true
