binary_sensor:
  - platform: gpio
    name: "${node_name} IN_01"
    id: in_01
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_01
    on_release:
      then:
        cover.stop: cover_01

  - platform: gpio
    name: "${node_name} IN_02"
    id: in_02
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_01
    on_release:
      then:
        cover.stop: cover_01

  - platform: gpio
    name: "${node_name} IN_03"
    id: in_03
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_02
    on_release:
      then:
        cover.stop: cover_02

  - platform: gpio
    name: "${node_name} IN_04"
    id: in_04
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_02
    on_release:
      then:
        cover.stop: cover_02

  - platform: gpio
    name: "${node_name} IN_05"
    id: in_05
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_03
    on_release:
      then:
        cover.stop: cover_03

  - platform: gpio
    name: "${node_name} IN_06"
    id: in_06
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_03
    on_release:
      then:
        cover.stop: cover_03

  - platform: gpio
    name: "${node_name} IN_07"
    id: in_07
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_04
    on_release:
      then:
        cover.stop: cover_04

  - platform: gpio
    name: "${node_name} IN_08"
    id: in_08
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_04
    on_release:
      then:
        cover.stop: cover_04

  - platform: gpio
    name: "${node_name} IN_09"
    id: in_09
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_05
    on_release:
      then:
        cover.stop: cover_05

  - platform: gpio
    name: "${node_name} IN_10"
    id: in_10
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_05
    on_release:
      then:
        cover.stop: cover_05

  - platform: gpio
    name: "${node_name} IN_11"
    id: in_11
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_06
    on_release:
      then:
        cover.stop: cover_06

  - platform: gpio
    name: "${node_name} IN_12"
    id: in_12
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_06
    on_release:
      then:
        cover.stop: cover_06

  - platform: gpio
    name: "${node_name} IN_13"
    id: in_13
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_07
    on_release:
      then:
        cover.stop: cover_07

  - platform: gpio
    name: "${node_name} IN_14"
    id: in_14
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_07
    on_release:
      then:
        cover.stop: cover_07

  - platform: gpio
    name: "${node_name} IN_15"
    id: in_15
    pin:
      pcf8574: pcf_inputs_15to28
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_08
    on_release:
      then:
        cover.stop: cover_08

  - platform: gpio
    name: "${node_name} IN_16"
    id: in_16
    pin:
      pcf8574: pcf_inputs_15to28
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_08
    on_release:
      then:
        cover.stop: cover_08

  - platform: gpio
    name: "${node_name} IN_17"
    id: in_17
    pin:
      pcf8574: pcf_inputs_15to28
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_09
    on_release:
      then:
        cover.stop: cover_09

  - platform: gpio
    name: "${node_name} IN_18"
    id: in_18
    pin:
      pcf8574: pcf_inputs_15to28
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_09
    on_release:
      then:
        cover.stop: cover_09

  - platform: gpio
    name: "${node_name} IN_19"
    id: in_19
    pin:
      pcf8574: pcf_inputs_15to28
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_10
    on_release:
      then:
        cover.stop: cover_10

  - platform: gpio
    name: "${node_name} IN_20"
    id: in_20
    pin:
      pcf8574: pcf_inputs_15to28
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_10
    on_release:
      then:
        cover.stop: cover_10

  - platform: gpio
    name: "${node_name} IN_21"
    id: in_21
    pin:
      pcf8574: pcf_inputs_15to28
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_11
    on_release:
      then:
        cover.stop: cover_11

  - platform: gpio
    name: "${node_name} IN_22"
    id: in_22
    pin:
      pcf8574: pcf_inputs_15to28
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_11
    on_release:
      then:
        cover.stop: cover_11

  - platform: gpio
    name: "${node_name} IN_23"
    id: in_23
    pin:
      pcf8574: pcf_inputs_15to28
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_12
    on_release:
      then:
        cover.stop: cover_12

  - platform: gpio
    name: "${node_name} IN_24"
    id: in_24
    pin:
      pcf8574: pcf_inputs_15to28
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_12
    on_release:
      then:
        cover.stop: cover_12

  - platform: gpio
    name: "${node_name} IN_25"
    id: in_25
    pin:
      pcf8574: pcf_inputs_15to28
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_13
    on_release:
      then:
        cover.stop: cover_13

  - platform: gpio
    name: "${node_name} IN_26"
    id: in_26
    pin:
      pcf8574: pcf_inputs_15to28
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_13
    on_release:
      then:
        cover.stop: cover_13

  - platform: gpio
    name: "${node_name} IN_27"
    id: in_27
    pin:
      pcf8574: pcf_inputs_15to28
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_14
    on_release:
      then:
        cover.stop: cover_14

  - platform: gpio
    name: "${node_name} IN_28"
    id: in_28
    pin:
      pcf8574: pcf_inputs_15to28
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_14
    on_release:
      then:
        cover.stop: cover_14

  - platform: gpio
    name: "${node_name} IN_29"
    id: in_29
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_15
    on_release:
      then:
        cover.stop: cover_15

  - platform: gpio
    name: "${node_name} IN_30"
    id: in_30
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_15
    on_release:
      then:
        cover.stop: cover_15

  - platform: gpio
    name: "${node_name} IN_31"
    id: in_31
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_16
    on_release:
      then:
        cover.stop: cover_16

  - platform: gpio
    name: "${node_name} IN_32"
    id: in_32
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        cover.open: cover_16
    on_release:
      then:
        cover.stop: cover_16

  - platform: gpio
    name: "${node_name} IN_33"
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 4
      mode:
        input: true
      inverted: true
      
  - platform: gpio
    name: "${node_name} IN_34"
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 5
      mode:
        input: true
      inverted: true
      
  - platform: gpio
    name: "${node_name} IN_35"
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 6
      mode:
        input: true
      inverted: true