#i2c addresses
# address: 0x26 input pcf io
# address: 0x27 input pcf io
# address: 0x3C input oled
# address: 0x40 input ina219 power
# address: 0x68 input rtc ds1307

binary_sensor:
  - platform: gpio
    name: "${node_name} IN_01"
    id: in_01
    pin:
      pcf8574: mcp_inputs_1to16
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_1

  - platform: gpio
    name: "${node_name} IN_02"
    id: in_02
    pin:
      pcf8574: mcp_inputs_1to16
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_2

  - platform: gpio
    name: "${node_name} IN_03"
    id: in_03
    pin:
      pcf8574: mcp_inputs_1to16
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_3

  - platform: gpio
    name: "${node_name} IN_04"
    id: in_04
    pin:
      pcf8574: mcp_inputs_1to16
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_4

  - platform: gpio
    name: "${node_name} IN_05"
    id: in_05
    pin:
      pcf8574: mcp_inputs_1to16
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_5

  - platform: gpio
    name: "${node_name} IN_06"
    id: in_06
    pin:
      pcf8574: mcp_inputs_1to16
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_6

  - platform: gpio
    name: "${node_name} IN_07"
    id: in_07
    pin:
      pcf8574: mcp_inputs_1to16
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_7

  - platform: gpio
    name: "${node_name} IN_08"
    id: in_08
    pin:
      pcf8574: mcp_inputs_1to16
      number: 7
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_8

  - platform: gpio
    name: "${node_name} IN_09"
    id: in_09
    pin:
      pcf8574: mcp_inputs_1to16
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_9

  - platform: gpio
    name: "${node_name} IN_10"
    id: in_10
    pin:
      pcf8574: mcp_inputs_1to16
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_10

  - platform: gpio
    name: "${node_name} IN_11"
    id: in_11
    pin:
      pcf8574: mcp_inputs_1to16
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_11

  - platform: gpio
    name: "${node_name} IN_12"
    id: in_12
    pin:
      pcf8574: mcp_inputs_1to16
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_12

  - platform: gpio
    name: "${node_name} IN_13"
    id: in_13
    pin:
      pcf8574: mcp_inputs_1to16
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_13

  - platform: gpio
    name: "${node_name} IN_14"
    id: in_14
    pin:
      pcf8574: mcp_inputs_1to16
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_14

  - platform: gpio
    name: "${node_name} IN_15"
    id: in_15
    pin:
      pcf8574: mcp_inputs_1to16
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_15

  - platform: gpio
    name: "${node_name} IN_16"
    id: in_16
    pin:
      pcf8574: mcp_inputs_1to16
      number: 15
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_16

  - platform: gpio
    name: "${node_name} IN_17"
    id: in_17
    pin:
      pcf8574: mcp_inputs_17to32
      number: 7
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_17

  - platform: gpio
    name: "${node_name} IN_18"
    id: in_18
    pin:
      pcf8574: mcp_inputs_17to32
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_18

  - platform: gpio
    name: "${node_name} IN_19"
    id: in_19
    pin:
      pcf8574: mcp_inputs_17to32
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_19

  - platform: gpio
    name: "${node_name} IN_20"
    id: in_20
    pin:
      pcf8574: mcp_inputs_17to32
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_20

  - platform: gpio
    name: "${node_name} IN_21"
    id: in_21
    pin:
      pcf8574: mcp_inputs_17to32
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_21

  - platform: gpio
    name: "${node_name} IN_22"
    id: in_22
    pin:
      pcf8574: mcp_inputs_17to32
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_22

  - platform: gpio
    name: "${node_name} IN_23"
    id: in_23
    pin:
      pcf8574: mcp_inputs_17to32
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_23

  - platform: gpio
    name: "${node_name} IN_24"
    id: in_24
    pin:
      pcf8574: mcp_inputs_17to32
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_24

  - platform: gpio
    name: "${node_name} IN_25"
    id: in_25
    pin:
      pcf8574: mcp_inputs_17to32
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_25

  - platform: gpio
    name: "${node_name} IN_26"
    id: in_26
    pin:
      pcf8574: mcp_inputs_17to32
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_26

  - platform: gpio
    name: "${node_name} IN_27"
    id: in_27
    pin:
      pcf8574: mcp_inputs_17to32
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_27

  - platform: gpio
    name: "${node_name} IN_28"
    id: in_28
    pin:
      pcf8574: mcp_inputs_17to32
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_28

  - platform: gpio
    name: "${node_name} IN_29"
    id: in_29
    pin:
      pcf8574: mcp_inputs_17to32
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_29

  - platform: gpio
    name: "${node_name} IN_30"
    id: in_30
    pin:
      pcf8574: mcp_inputs_17to32
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_30

  - platform: gpio
    name: "${node_name} IN_31"
    id: in_31
    pin:
      pcf8574: mcp_inputs_17to32
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_31

  - platform: gpio
    name: "${node_name} IN_32"
    id: in_32
    pin:
      pcf8574: mcp_inputs_17to32
      number: 15
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay_32

  - platform: gpio
    name: "${node_name} IN_33"
    pin:
      number: GPIO33
      mode:
        input: true
      inverted: true
      
  - platform: gpio
    name: "${node_name} IN_34"
    pin:
      number: GPIO17
      mode:
        input: true
      inverted: true
      
  - platform: gpio
    name: "${node_name} IN_35"
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
      inverted: false

